In [2]:
import pandas as pd

In [8]:
path = 'D:/UFPR/2º Semestre 2021/Estatística Econômica e Introdução à Econometria/1. Relatório Enade/2018/3.DADOS/microdados_enade_2018.txt' # caminho do arquivo
enade = pd.read_table(path, sep=';')

In [11]:
enade[enade.CO_GRUPO==13]

,NU_ANO,CO_IES,CO_CATEGAD,CO_ORGACAD,CO_GRUPO,CO_CURSO,CO_MODALIDADE,CO_MUNIC_CURSO,CO_UF_CURSO,CO_REGIAO_CURSO,...,QE_I59,QE_I60,QE_I61,QE_I62,QE_I63,QE_I64,QE_I65,QE_I66,QE_I67,QE_I68
160,2018,1780,10008,10022,13,81867,1,4309605,43,4,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
161,2018,1780,10008,10022,13,81867,1,4309605,43,4,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
162,2018,1780,10008,10022,13,81867,1,4309605,43,4,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
163,2018,1780,10008,10022,13,81867,1,4309605,43,4,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
164,2018,1780,10008,10022,13,81867,1,4309605,43,4,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547635,2018,316,10008,10028,13,66277,1,3550308,35,3,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
547636,2018,316,10008,10028,13,66277,1,3550308,35,3,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
547637,2018,316,10008,10028,13,66277,1,3550308,35,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547638,2018,316,10008,10028,13,66277,1,3550308,35,3,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
548122,2018,1723,10008,10022,13,1105114,1,3547809,35,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN